<?php

    namespace PropertiesManager;

    use App\Core\Plugin\AppBasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for PropertiesManager
     */
    class Plugin extends AppBasePlugin
    {

        public function routes($routes)
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $this->setMenus([
                ['url'      => '#',
                 'label'    => __('Biens'),
                 'order'    => 0,
                 'icon'     => '<i class="fa fa-building"></i>&nbsp;',
                 'submenus' => [
                     ['url'   => Router::url(['controller' => 'Properties',
                                              'action'     => 'add',
                                              'plugin'     => 'PropertiesManager']),
                      'label' => __('Créer un bien'),
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => '',
                      'label' => '-',
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => Router::url(['controller' => 'Properties',
                                              'action'     => 'index',
                                              'plugin'     => 'PropertiesManager']),
                      'label' => __('Lister les biens'),
                      'order' => 0,
                      'icon'  => ''],
                 ]
                ]
            ]);
        }
    }
