<?php

    namespace TiersManager;

    use App\Core\Plugin\AppBasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for CustomersManager
     */
    class Plugin extends AppBasePlugin
    {
        public function routes($routes)
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $this->setMenus([
                ['url'      => '#',
                 'label'    => __('Tiers'),
                 'order'    => 0,
                 'icon'     => '<i class="fa fa-sitemap"></i>&nbsp;',
                 'submenus' => [
                     ['url'   => Router::url(['controller' => 'Customers',
                                              'action'     => 'add',
                                              'plugin'     => 'TiersManager']),
                      'label' => __('Créer un client'),
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => Router::url(['controller' => 'Suppliers',
                                              'action'     => 'add',
                                              'plugin'     => 'TiersManager']),
                      'label' => __('Créer un fournisseur'),
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => '',
                      'label' => '-',
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => Router::url(['controller' => 'Customers',
                                              'action'     => 'index',
                                              'plugin'     => 'TiersManager']),
                      'label' => __('Lister les clients'),
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => Router::url(['controller' => 'Suppliers',
                                              'action'     => 'index',
                                              'plugin'     => 'TiersManager']),
                      'label' => __('Lister les fournisseurs'),
                      'order' => 0,
                      'icon'  => ''],
                 ]
                ]
            ]);
        }
    }
