<?php
    declare(strict_types=1);

    namespace AppPluginsManager;

    use App\Core\Menu\AppMenu;
    use Cake\Core\BasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for AppPluginsManager
     */
    class AppPlugin extends BasePlugin
    {

        public function routes($routes): void
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $subMenu = new AppMenu(Router::url(['controller' => 'AppPlugins',
                'action' => 'index',
                'plugin' => 'AppPluginsManager']), __('Liste des plugins'), 0, '');
            $this->addSubmenu('Configuration', 'right', [$subMenu]);
        }


    }
