<?php

    namespace AppPluginsManager;

    use App\Core\Menu\AppMenu;
    use App\Core\Plugin\AppBasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for AppPluginsManager
     */
    class Plugin extends AppBasePlugin
    {

        public function routes($routes): void
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $subMenu = new AppMenu(
                Router::url(
                    [
                        'controller' => 'AppPlugins',
                        'action'     => 'index',
                        'plugin'     => 'AppPluginsManager'
                    ]
                ), __('Liste des plugins'), 0, ''
            );
            $this->addSubmenu('Configuration', 'right', [$subMenu]);
        }


    }
