<?php

    namespace ExamplePlugin;

    use App\Core\Menu\AppMenu;
    use App\Core\Plugin\AppBasePlugin;

    /**
     * Plugin for ExamplePlugin
     */
    class Plugin extends AppBasePlugin
    {
        protected $extendFields = [
            'TiersManager\Model\Entity\Customer' => [
                'new_prop' => ['type'    => 'integer',
                               'options' => [
                                   'null' => TRUE]]
            ]];

        protected $hooks = [
            'OperationsManager.Operations.step1.action'       => 'CellSample',
            'OperationsManager.Operations.step1.beforeinputs' => 'new_input',
        ];

        public function routes($routes)
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $this->setMenus([
                ['url'      => '#',
                 'label'    => 'Example plugin',
                 'order'    => 0,
                 'position' => 'right',
                 'icon'     => '<i class="fa fa-question"></i>&nbsp;',
                 'submenus' => []
                ]], 'ExamplePlugin');

            $submenus = new AppMenu('#', 'test config', 0, '');
            $this->addSubmenu('Configuration', 'right', [$submenus]);

        }
    }
