FROM php:7.4-fpm
RUN apt-get update && apt-get install -y \
        libicu-dev \
        unzip \
        vim \
        libzip-dev \
        libpng-dev \
        libonig-dev \
        zip \
        nodejs \
        gnupg \
        npm \
        wget \
        curl \
        jq \
        sudo \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd
RUN pecl install xdebug-2.8.1 && docker-php-ext-enable xdebug
RUN docker-php-ext-configure intl
RUN docker-php-ext-configure opcache --enable-opcache
RUN docker-php-ext-install -j$(nproc) opcache pdo_mysql mbstring gd intl zip bcmath json
