<?php

    namespace Wizardinstaller\Controller;

    use App\Controller\AppController as BaseController;
    use Cake\Event\EventInterface;

    /**
     * Class AppController
     *
     * @package Wizardinstaller\Controller
     */
    class AppController extends BaseController
    {
        public function initialize(): void
        {
            parent::initialize(); // TODO: Change the autogenerated stub
        }


        /**
         * Before render callback.
         *
         * @param  EventInterface  $event  The beforeRender event.
         * @return void
         */
        public function beforeRender(EventInterface $event)
        {
            $this->viewBuilder()
                 ->setLayout('Wizardinstaller.default');
        }

    }
