<?php

    namespace CompaniesManager;

    use App\Core\Plugin\AppBasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for CompaniesManager
     */
    class Plugin extends AppBasePlugin
    {
        public function routes($routes): void
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $this->setMenus(
                [
                    [
                        'url'      => '#',
                        'label'    => __('Sociétés'),
                        'order'    => 0,
                        'icon'     => '<i class="fa fa-bank"></i>&nbsp;',
                        'submenus' => [
                            [
                                'url'   => Router::url(
                                    [
                                        'controller' => 'Companies',
                                        'action'     => 'add',
                                        'plugin'     => 'CompaniesManager'
                                    ]
                                ),
                                'label' => __('Créer une société'),
                                'order' => 0,
                                'icon'  => ''
                            ],
                            [
                                'url'   => '',
                                'label' => '-',
                                'order' => 0,
                                'icon'  => ''
                            ],
                            [
                                'url'   => Router::url(
                                    [
                                        'controller' => 'Companies',
                                        'action'     => 'index',
                                        'plugin'     => 'CompaniesManager'
                                    ]
                                ),
                                'label' => __('Lister les sociétés'),
                                'order' => 0,
                                'icon'  => ''
                            ]
                        ]
                    ]
                ]
            );
        }
    }
