<?php

    namespace OperationsManager;

    use App\Core\Plugin\AppBasePlugin;
    use Cake\Routing\Router;

    /**
     * Plugin for OperationsManager
     */
    class Plugin extends AppBasePlugin
    {
        public function routes($routes)
        {
            parent::routes($routes); // TODO: Change the autogenerated stub
            $this->setMenus([
                ['url'      => '#',
                 'label'    => __('Operations'),
                 'order'    => 0,
                 'icon'     => '<i class="fa fa-newspaper-o"></i>&nbsp;',
                 'submenus' => [
                     ['url'   => Router::url(['controller' => 'Operations',
                                              'action'     => 'step1',
                                              'plugin'     => 'OperationsManager']),
                      'label' => __('Créer une opération'),
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => '',
                      'label' => '-',
                      'order' => 0,
                      'icon'  => ''],
                     ['url'   => Router::url(['controller' => 'Operations',
                                              'action'     => 'index',
                                              'plugin'     => 'OperationsManager']),
                      'label' => __('Liste des opérations'),
                      'order' => 0,
                      'icon'  => ''],
                 ]
                ]
            ]);
        }
    }
